### ISSUE TITLE
Rolování k poslednímu prečtenému

### ISSUE THREAD

**Issue by Megharadzor** [lucien144/fyx#117]
Šlo by prosím udělat aby když vidím, že má klub 20 neprectenych příspěvků po otevření okno sjelo k poslednímu přečtenému a já si pěkně postupně přečetl ty nové? Bylo by to super. Díky

**Comment by lucien144** [comment]
@Megharadzor Ano, podívám se na to, už se po tom někdo ptal.

**Comment by Megharadzor** [comment]
To by bylo skvělé

**Comment by Megharadzor** [comment]
> @Megharadzor Ano, podívám se na to, už se po tom někdo ptal.

To by bylo super! Díky

**Comment by Megharadzor** [comment]
To je skvělá zprava. Díky

**Comment by lucien144** [comment]
https://github.com/quire-io/scroll-to-index
