### ISSUE TITLE
Po nahrání obrázku se i při blikajícím kurzoru schová klávesnice

### ISSUE THREAD

**Issue by koc256** [lucien144/fyx#119]
Po nahrání obrázku se i při blikajícím kurzoru schová klávesnice.
![IMG_4416](https://user-images.githubusercontent.com/64221259/100214648-6bd47500-2f10-11eb-942a-88e36f5cda57.PNG)

**Comment by lucien144** [comment]
Tohle jsem uz pakrat videl a zazil, ale bohuzel to je trochu neresitelny problem. Deje se to jen obcas, nic pri tom nepada atp... Pouzivas nejakou klavesnici tretich stran?

**Comment by lucien144** [comment]
@koc256 Mozna jsem to jen spatne pochopil... ta klavesnice zmizi kdyz nahrajes fotku, ale dalsim tapnutim do toho inputboxu s kurzorem se zase objevi? To je to co reportujes?

**Comment by koc256** [comment]
> @koc256 Mozna jsem to jen spatne pochopil... ta klavesnice zmizi kdyz nahrajes fotku, ale dalsim tapnutim do toho inputboxu s kurzorem se zase objevi? To je to co reportujes?

Ano. Před započetím nahrávání mám klávesnici otevřenou. Přišlo by mi logické to mít stejně i po dokončení nahrávání obrázku...

**Comment by koc256** [comment]
> Tohle jsem uz pakrat videl a zazil, ale bohuzel to je trochu neresitelny problem. Deje se to jen obcas, nic pri tom nepada atp... Pouzivas nejakou klavesnici tretich stran?

Děje se mi to vždy, nepoužívám nic mimo iOS native...

**Comment by lucien144** [comment]
@koc256 Jasne, tohle umim reprodukovat a asi i fixnout, tohle je bug.
