### ISSUE TITLE
Rozbité ankety

### ISSUE THREAD

**Issue by lucien144** [lucien144/fyx#149]

**Comment by kejml** [comment]
@lucien144 Jestli se na tohle vyloženě nechystáš, tak jsem s tímhle začal

**Comment by lucien144** [comment]
@kejml Super. Kdyžtak se podívej do https://github.com/lucien144/fyx/tree/feature/new-api-updates - už tam pro to jsou připravené nějaké modely.

**Comment by kejml** [comment]
Bezva, to se bude hodit
