### ISSUE TITLE
Notifikace v oznamovacím centru

### ISSUE THREAD

**Issue by s2fiGIT** [lucien144/fyx#150]
**Popis chyby**
1 nová zpráva v poště - zacyklené notifikace

**Očekávané chování**
1 nová zpráva v poště = 1 notifikace v oznamovacím centru

**Screenshoty**
Pokud lze, přidejte screenshoty chyby.
![notifikace](https://user-images.githubusercontent.com/81738888/113255332-ffa3bc80-92c7-11eb-9f4a-284bf79dff07.jpeg)

**Informace o systému:**
 - Typ telefonu: iPhone SE
 - Verze iOS: iOS14.0.1
 - Verze Fyxu: 0.5.0

**Comment by lucien144** [comment]
Uzavírám. Je to problém Nyxu, potvrzeno samotným Nyxem.
