### ISSUE TITLE
Po uspání a probuzení aplikace může diskuze odsrolovat jinam

### ISSUE THREAD

**Issue by lucien144** [lucien144/fyx#159]
Když čtu nějakou dlouhou a aktivní diskuzi a zamknu telefon (nebo přepnu do jiné aplikace), tak po návratu do Fyxu se načtou nové příspěvky, čímž celý pohled na diskuzi odskroluje jinam než před tím a já musím hledat co jsem přečetl

---

| Uživatel | Verze | Telefon | OS | Odkaz |
|---|---|---|---|---|
| ID KEJML | 0.6.0 (3) | Pixel 4a | sunfish REL(?? to se vyplnilo samo, mám Android 11) |  |

**Comment by kejml** [comment]
Překlep v titulku, má být po místo pro :)

**Comment by lucien144** [comment]
@kejml Souvisi tak trochu s #18. Uz jsem nad tim premyslel....

**Comment by kejml** [comment]
Tak tu souvislost nedokážu nahlédnout :) Ale v tohle případě si to označení nepřečtených pamatuje dobře

Ještě s tím souvisí, že když probudím Fyx mimo signál, tak místo abych mohl pokračovat číst aspoň to načtené, tak dostanu chybovou hlášku. Dá se to řešit současně, nebo mám založit ještě jednu issue?

**Comment by lucien144** [comment]
@kejml Asi založ novou, pls.
