### ISSUE TITLE
Špatné zobrazení anket

### ISSUE THREAD

**Issue by lucien144** [lucien144/fyx#167]
Jak v upomínkách, že se něco stalo, tak v klubu samotném

---

| Uživatel | Verze | Telefon | OS | Odkaz |
|---|---|---|---|---|
| ID koc256 | 0.6.1 | iP 12 mini | 14.4.1 (poslední stable) |  |

**Comment by koc256** [comment]
![IMG_0465](https://user-images.githubusercontent.com/64221259/114141682-373ae600-9912-11eb-9f3b-20e6b0fea392.PNG)
![IMG_0466](https://user-images.githubusercontent.com/64221259/114141686-386c1300-9912-11eb-8162-512cfecb227c.PNG)

**Comment by lucien144** [comment]
Vím. Bylo to v release notes že tohle jsem nestihl.

**Comment by koc256** [comment]
Tak OK. Sry :)

**Comment by lucien144** [comment]
duplicate #149
