### ISSUE TITLE
Přehazování pořadí diskusí po přečtení

### ISSUE THREAD

**Issue by skaffff** [lucien144/fyx#181]
Je to asi spíš UX / věc zvyku / možná blbost, ale:

Když jsem v history > vlezu do nějaké diskuse > čtu > pak swipe right > objevim se zpět v seznamu diskusí

Diskuse, do které jsem vlezl naposled, mi skočí nahoru v seznamu, což bych čekal, že se stane až potom, co refreshnu seznam diskusí manuálně (swipe down) případně odejdu někam úplně jinam (třeba do pošty) a zase se vrátim do historie. 

Důvod, proč mi to vadí je ten, že vizuálně vidím v historii seznam a podvědomě vim, že mě zajímám např. ústav, pak třeba komiksy, ale když vlezu do ústavu a vrátim se zpět, tak komiksy jsou už na jiném místě v seznamu. Ale můj prst automaticky klikne tam, kde očekává komiksy (tzn kde byly v seznamu předtím). Jenže tam už je něco jiného, protože se seznam posunul o řádek :)

**Comment by lucien144** [comment]
Chápu, ale tohle bude hodně subjektivní a navíc se takhle chová i web. Nebudu to zatím zavírat, ale aktuálně si nemyslím, že se to do app dostane...

**Comment by skaffff** [comment]
vypadá to, že jsem si na to po dvou dnech zvykl
