### ISSUE TITLE
Podmínečné formátování postů v závislosti na hodnocení postu (+/-)

### ISSUE THREAD

**Issue by skaffff** [lucien144/fyx#184]
(driv to nekde kdesi fungovalo)

Pokud to jde, rád bych viděl posty v podmínečném formátování, kdy post který má plus X je výraznější, plus XX je ještě výraznější a plus XXX je ještě víc výrazný. Border, barva, něco.

Naopak minux X je opacity 90, minus XX je opacity 50 a minus XXX je opacity 10. Je dobry mit možnost opacity zrušit na dobu, kdy na něm držím prst.

_V exponovaných klubech, kde zůstavají jen dobré posty s plus XXX budou výrazné všechny, ale vymýšlet nějaký formátování na základe relativní hodnoty příspěvku v rámci klubu je asi moc velká úchylárna._

**Comment by lucien144** [comment]
Tohle je již víceméně hotové. Zavírám.
