### ISSUE TITLE
Malá ikona na Androidu

### ISSUE THREAD

**Issue by kejml** [lucien144/fyx#193]
Ikona aplikace je menší, než je na Androidu zvykem - viz screenshot 
![Screenshot_20210415-093243~2](https://user-images.githubusercontent.com/4223239/114838807-5f748a00-9dd5-11eb-9bcd-2488697b73b8.png)

**Comment by kejml** [comment]
@lucien144 Hlásím v aktuální verzi úspěšně opravené

**Comment by lucien144** [comment]
@kejml wtf? s tim jsem nic nedelal :D

**Comment by kejml** [comment]
Akorát teď koukám, že i když mám v systému u všech aplikací kulatý rohy, tak Fyx na ostrý. Ještě to večer prostuduju a screenshotnu

**Comment by kejml** [comment]
Tak to byl asi jen nějakej dočasnej glitch u mne. Po upgradu je ikonka malá jako dřív a ani downgradem už jsem to nezrprodukoval
