### ISSUE TITLE
Zaporne hodnoty u neprectenych prispevku

### ISSUE THREAD

**Issue by d4nys3k** [lucien144/fyx#194]
**Popis chyby**
Nekdy se u poctu neprectenych prispevku objevi zaporna hodnota

**Screenshoty**
![Screenshot_2021-04-15_11-14-05](https://user-images.githubusercontent.com/16295884/114845076-b8472100-9ddb-11eb-9640-2555e1a54c2a.png)

**Informace o systému:**
 - Typ telefonu: Samsung
 - Verze Android: 11
 - Verze Fyxu 0.7.0(1)

**Comment by aditucz** [comment]
Dtto Android 7.1.2, tel. Xiaomi Redmi 4X global, zatím jen jednou, nedaří se mi zreplikovat. Možná nějaký zbytek po mazání v klubu od minulé návštěvy? 
![Screenshot_2021-04-14-13-53-59-501_net lucien144 fyx](https://user-images.githubusercontent.com/82514644/114907060-fa438780-9e1a-11eb-8a2b-d9aa3b10bab7.jpg)

**Comment by lucien144** [comment]
Už jsem si toho sám všiml. Musím to prozkoumat, než začnu prudit Nyxe, ale mám tušení, že to bude právě tím mazáním... Nicméně fix by měl být easy.

**Comment by Toomix** [comment]
Taky doplním - zobrazilo se -11, po vstupu do diskuze jsem viděl 4 nové příspěvky. Jen mi to je divné, v Dětských perlách se snad ani nemaže.

Android 9
FYX 0.7.0

![Screenshot_2021-04-15-20-07-05-582_net lucien144 fyx_copy_1080x214](https://user-images.githubusercontent.com/26710343/114917804-a76fcd00-9e26-11eb-9e58-ed3e6aa4e7c0.jpg)

**Comment by lucien144** [comment]
Skutečně to posílá Nyx...

![https://cln.sh/9W8Nq2+](https://cln.sh/9W8Nq2+)

**Comment by Toomix** [comment]
Ano, to je jedna soukromá diskue ;)

**Comment by lucien144** [comment]
No spíš přemýšlím, jestli je to k něčemu dobré...
