### ISSUE TITLE
Spoiler ve kterém je pouze obrázek nelze zobrazit

### ISSUE THREAD

**Issue by kejml** [lucien144/fyx#308]
**Jak to reprodukovat**
https://nyx.cz/discussion/14158/id/54701886

**Informace o systému:**
 - Verze Fyxu 0.8.3 (52)

**Comment by lucien144** [comment]
Fixnuto.
![Simulator Screen Shot - iPhone 13 - 2022-05-13 at 22 36 09](https://user-images.githubusercontent.com/5161085/168385953-97f06fe7-8227-41e6-8ee4-43916220cad5.png)
