### ISSUE TITLE
Otazník místo názvu jedné diskuze

### ISSUE THREAD

**Issue by kejml** [lucien144/fyx#312]
**Popis chyby**
Diskuze  https://nyx.cz/discussion/275939 se v seznamu diskuzí zobrazí normálně, ale po otevření je v titulku jen otazník. Jiné diskuze s emotikony fungují, tak nevím, jestli tyhle jsou speciální, nebo je příčina jiné

![Screenshot_20220324-114007](https://user-images.githubusercontent.com/4223239/159898970-d98c2be8-f5bf-4ec0-b7f1-77070cd64c5e.png)

![Screenshot_20220324-113950](https://user-images.githubusercontent.com/4223239/159898985-25ce838e-3f3a-437e-9f74-fea5ee58b7c5.png)

**Informace o systému:**
 - Typ telefonu: Pixel 4a
 - Verze OS: Android 12
 - Verze Fyxu 0.8.3

**Comment by lucien144** [comment]
Vtipny je, ze tooltip funguje ok.
