### ISSUE TITLE
Scroll od prvniho neprecteneho poskakuje

### ISSUE THREAD

**Issue by lucien144** [lucien144/fyx#334]
> Chtel bych se zeptat na donacitani obrazku kdyz jdu od spodu nahoru. V klubech kde je hodne obrazku to velmi silne odskakuje na jine pozice a ta experience je dost protivna. Myslim ze by to lidi co ctou timto zpusobem mohlo zacit dost stvat. Osobne to vnimam jako neco cim by se vyplatilo zabyvat co nejdrive bude sila a cas. Neni-li tam tech. limit. Co myslite?

Reference:
- https://stackoverflow.com/questions/71175960/is-it-possible-to-have-a-listview-maintain-its-position-as-images-of-variable-he
- https://stackoverflow.com/questions/44665955/how-do-i-determine-the-width-and-height-of-an-image-in-flutter

**Comment by kejml** [comment]
Related: #204
