### ISSUE TITLE
Automatické hledání po napsání pár znaků schová klávesnici

### ISSUE THREAD

**Issue by kejml** [lucien144/fyx#340]
**Jak to reprodukovat**
1. Chci v klubu hledat příspěvky od ID LUCIEN
2. Kliknu na hledání, začnu psát `@luc`
3. Hledaný string se automaticky submitne
4. Nastanou dva problémy:
    1. Zmizí mi klávesnice
    2. Zobrazí se stránka `Wow. Such empty`

**Očekávané chování**
Dobrá otázka na naše UX experty. Možná nějaký delay před tím, než se hledaný string submitne?

**Informace o systému:**
 - Typ telefonu: Pixel 4a
 - Verze OS: Android 12
 - Verze Fyxu 0.9.0 (66)

**Comment by lucien144** [comment]
Bylo mi jasný, že ten Travolta tady bude problém. Jde o to, že ten prázdný screen je samostatný widget, tedy i ten searchbox je jiný widget a proto se zahodí focus...

Zkusím nad tím zapřemýšlet...
