### ISSUE TITLE
Rozbité tučné velké písmo

### ISSUE THREAD

**Issue by kejml** [lucien144/fyx#354]
**Popis chyby**
Viz screenshoty

**Screenshoty**
![Screenshot_20220822-202800](https://user-images.githubusercontent.com/4223239/186014851-75aec780-6abe-43c5-aca1-78edf0b8ee0b.png)

![Screenshot_20220822-224130](https://user-images.githubusercontent.com/4223239/186015136-1b68dd0c-c4c4-4fd1-ad1a-6af94b6a3d55.png)

**Informace o systému:**
 - Typ telefonu: Pixel 4a
 - Verze OS: Android 13
 - Verze Fyxu: 0.9.0 (68)

**Comment by lucien144** [comment]
Tohle je pouze Android related a děje se mi to i na mém Redmi. Takže to nesouvisí s verzí OS imho.

Nová verze běží na Flutter 3 - může to být tím...

**Comment by lucien144** [comment]
Zda se, ze to je problem primo Interu. Nahlasil jsem to https://github.com/material-foundation/google-fonts-flutter/issues/258, tak uvidime. Zatim jsem Inter z Androidu odebral.
