### ISSUE TITLE
Možnost otevřít odkazy v plném browseru

### ISSUE THREAD

**Issue by kejml** [lucien144/fyx#356]
**Má navrhovaná nová funkce řešit nějaký problém? Popiště to...**
Dřív kliknutí na odkaz otevřelo browser jako samostatnou aplikaci. Od posledni verze (0.9.0 (70)) se otevírá jen jakési webview, které má několik nevýhod:
* Nelze si otevřít odkaz na později (a mezitím se vrátit do Fyxu)
* V tom webview nefunguje automatické přihlášení na webech, kde ho mám zaplé (hádám, že nesdílí cookies s browserem, nebo tak něco)
* Nelze si daný odkaz zkopírovat z browseru a použít na něco dalšího

**Popište navrhované řešení.**
Za mne byl ideální předchozí stav, kdy se prostě otevřel browser.

**Popište další možnosti řešení.**
Druhá možnost je to, co dělá čím dál víc aplikací, že to webview má dole nástrojovou lištu, na které je mj. menu s možností otevřít aktuální stránku v plnotučném browseru. Řešení to je, ale pro mne to jsou ve většinu případů dva kliky navíc

**Comment by lucien144** [comment]
To je zajímavý. Měl jsem za to, že se to ve webview otevírá od začátku, resp. u iOS to tak je. 

Tohle asi bude muset do nastavení, kdybych to změnil i pro iOS, tak budou lidi prskat (včetně mě, webview mi vyhovuje).

**Comment by kejml** [comment]
I to webview bych zvládnul, kdyby v něm byla ta ovládací lišta, léta teď ve Fyxu chybí, je tam jen full screen web

**Comment by lucien144** [comment]
https://github.com/flutter/flutter/issues/106331
