### ISSUE TITLE
Nezobrazuje se kod v prispevku (asi tag xmp?)

### ISSUE THREAD

**Issue by kejml** [lucien144/fyx#361]
**Popis chyby**
Ve Fyxu (v dark módu) nevidím kus prispevku, ktery se na webu zobrazuje jako html kod: https://nyx.cz/discussion/1/id/55208148

**Informace o systému:**
 - Typ telefonu: Pixel 4a
 - Verze iOS: Android 13
 - Verze Fyxu 0.9.0 (72)

**Comment by lucien144** [comment]
Veškeré `XMP` se převádějí na `PRE` zde https://github.com/lucien144/fyx/blob/5a5988959124f648ce3ac44d4a9a155f0b8cb53d/lib/model/post/content/Regular.dart#L115

Problém tak nebyl v `XMP`, ale v obsahu - tady šlo o `HTML`, které html parser převedl na `HTML` a Fyx se to tedy pokusil vykreslit... Řešení bylo lehké - escapovat obsah XMP, otázkou pak zůstává, zda to nedělat i pro `PRE` - tady je ale potřeba zjistit, zda se u `PRE` parser nechová jinak.

Další věcí je, že by chtěl ten escaping přepsat, [tohle](https://github.com/lucien144/fyx/blob/5a5988959124f648ce3ac44d4a9a155f0b8cb53d/lib/model/post/content/Regular.dart#L116) asi nebude nejrychlejší. Ale je to okrajová věc, tak zatím nechávám být...
