### ISSUE TITLE
Nelze otevřít odkaz v prohlížeči

### ISSUE THREAD

**Issue by kejml** [lucien144/fyx#364]
**Popis chyby**
Odkaz hlásí "Nepodařilo se otevřít prohlížeč". Teoreticky může souviset s tím, že mám nainstalovanou i Reddit appku (ale nemusí)

**Jak to reprodukovat**
https://nyx.cz/discussion/6576/id/55226411

**Informace o systému:**
 - Typ telefonu: Pixel 4a
 - Verze iOS: Android 13
 - Verze Fyxu: 0.9.0 (75)

Edit @lucien144: _Nastavení odkazů je otevírat je ve Fyxu. Otevírání v externí app je ok._

**Comment by kejml** [comment]
Stejná hláška se zobrazí i když přepnu Fyx, aby používal webview

**Comment by lucien144** [comment]
@kejml Jsem trochu bezradnej tady - dela to jen Reddit nebo i dalsi appky co mas nainstalovany (treba Twitter?)

**Comment by kejml** [comment]
Aktuálně se to chová trochu jinak. Zjistil jsem teď přepnout na webview a otevřít twitter. Otevřete se webová stránka s tweetem, což je ok. Stránka ale nabízí možnost otevřít tweet v aplikaci, a na to post kliknu, tak dostanu chybu, že každý se navíc nedá dostat jinak, než zabitím Fyxu (gesto zpět nic nedělá). 

![Uploading Screenshot_20221101-102426.png…]()

**Comment by lucien144** [comment]
@kejml Asi muzeme zavrit viz. [#380](https://github.com/lucien144/fyx/issues/380) ne?

**Comment by kejml** [comment]
Jo, za mě jo, zapomněl jsem, že tu ten ticket je :)
