### ISSUE TITLE
Tweety vložené odkazem by se měly odlišit od běžného textu

### ISSUE THREAD

**Issue by kejml** [lucien144/fyx#369]
Nyx nové po vložení odkazu na Twitter vkládá text tweetu přímo do příspěvku. Na webu je text vizuálně oddělen, ale ve Fyxu ne.

**Comment by lucien144** [comment]
@kejml Co takhle?

![Image](https://user-images.githubusercontent.com/5161085/199112895-e605d545-eca1-4ffe-a78c-a163e731f9a1.png)

**Comment by kejml** [comment]
Jo, to je pěkný :)
