### ISSUE TITLE
Zavření náhledu obrázku klikem mimo obrázek

### ISSUE THREAD

**Issue by wojtishek** [lucien144/fyx#42]
aktuálně lze zavřít pouze křížkem

**Comment by wojtishek** [comment]
zkusil jsem znovu a opravdu funguje, jen je tam prodleva, se kterou jsem nepočítal.
iP7, iOS 13.3.1

**Comment by lucien144** [comment]
O tom delayi vím. Už jsem si zvyknul, ale taky mě to ze začátku štvalo. Bohužel je tam problém v GestureDetectoru, takže tam budu muset přijít na nějaký workaround.

Nicméně to jako velkou prioritu nevidím když  nebudu schopný najít rychlý fix. Ale zkusím to před notifikacemi.

**Comment by wojtishek** [comment]
Jeste upravim zjistene chovani - pokud se snazim zavrit klikem mimo fotku a kliknu po cele sirce bloku, ve kterem je cislo fotky / celkem fotek, tak zavreni nefunguje.

**Comment by lucien144** [comment]
91753088de25c2caed1ab51281908a633b8054c9
