### ISSUE TITLE
Nefunguje custom klávesnice pro zadání username

### ISSUE THREAD

**Issue by vidocq01** [lucien144/fyx#43]
Procházím wizardem pro první přihlášení. Dojdu až k linku na otevření nyx ve webview. Když chci vyplnit username tak klávesnice nereaguje
Klávesnice je SwiftKey.
Fyx 0.3.0
iPhone 11 iOS 13.3.1

**Comment by vidocq01** [comment]
Jo to je to chyba libovolného linku otevřeného přes Fyx.

**Comment by lucien144** [comment]
Neumím replikovat. Taky používám Swift, a nemám problém. Nicméně tohle bude asi problém vyřešit... zatím nebudu řešit a uvidíme zda se ozve víc lidí. 

Můj screen:
![image](https://user-images.githubusercontent.com/5161085/79905513-b9a86c80-8459-11ea-8953-11b1da5254b0.png)

**Comment by lucien144** [comment]
@vidocq01 Mimochodem, to webview je obyčejné Safari. V něm ti SwiftKey, ideálně přímo na login screenu Nyxův, jede?

**Comment by fieldmanneasi** [comment]
Odzkoušeno na iPhone 8 s poledním iOS a SwiftKey a jede bez problémů.
