### ISSUE TITLE
Nezobrazují se náhledy na linky

### ISSUE THREAD

**Issue by vidocq01** [lucien144/fyx#44]
Fyx 0.3.0
iOS 13.3.1

![9C82A600-D619-42D0-8A44-F271FA0F0AD1](https://user-images.githubusercontent.com/26001006/79897281-c3a27f00-8409-11ea-8e2e-20a17908b258.png)

![5D9F9789-2238-4225-98A3-1A409B958481](https://user-images.githubusercontent.com/26001006/79897272-c00ef800-8409-11ea-9cba-e70deb70306f.png)

**Comment by lucien144** [comment]
To ani nelze. Nyx to nepředává a dělat to v appce je nesmysl. Pokud příspěvek obsahuje jen odkazy, z prvního se udělá takovýto HeroBox a to je vše. Tohle je spíše na diskuzi ohledně UI/UX, zda jsou ty boxy dobře. U obrázků to asi dává smysl, tady možná ne...
