### ISSUE TITLE
Přehled klubů občas vyhodí chybu

### ISSUE THREAD

**Issue by fieldmanneasi** [lucien144/fyx#50]
**Popis chyby**
Nspecifická akce občas vyhodí chybové okno.

**Jak to reprodukovat**
Nepodařilo se mi zjistit, co to způsobuje. 

**Screenshoty**
![IMG_5799](https://user-images.githubusercontent.com/20816701/79966413-afa06100-848d-11ea-89af-2162cd942ec1.PNG)

**Informace o systému:**
 - Typ telefonu: iPhone 7
 - Verze iOS: iOS13.3.1
 - Verze Fyxu: 0.3.0 (5)

**Comment by lucien144** [comment]
@fieldmanneasi Nekolísá ti připojení k netu, např. že se připojuješ různě mezi wifi a 3g? Tohle znamená, že jsi de facto offline - alespoň ve chvíli, kdy se app pokusí refreshnout data...

**Comment by fieldmanneasi** [comment]
To je možný. Mám barák jak faradayovu klec se slepejma místama tak vyzkouším nějak až budu doma...

**Comment by fieldmanneasi** [comment]
Tak je to připojením... Zavírám
