### ISSUE TITLE
Chyba zobrazení příspěvku

### ISSUE THREAD

**Issue by vidocq01** [lucien144/fyx#53]
**Zdroj:**
```<video controls="controls"><br />
<source src="https://cdntube2.b-cdn.net/mp4/09fa1d999960f65d96cc35f92905e4184e292793.mp4" type="video/mp4"><br />
</video>```

---
*Verze: 0.3.0 (5)
iOS: iOS 13.3.1 iPhone*

**Comment by lucien144** [comment]
@vidocq01 Mohl bys mi sem poslat odkaz primo na prispevek na nyxu? Dik.

**Comment by vidocq01** [comment]
Jasně 

https://www.nyx.cz/index.php?l=topic;id=45;wu=51939926;n=c795

**Comment by lucien144** [comment]
@vidocq01 Bude vyřešeno v novém buildu, viz:

![image](https://user-images.githubusercontent.com/5161085/81048407-91d6f100-8ebc-11ea-89b8-e6a094dcd319.png)
