### ISSUE TITLE
UI/UX: Zvýraznění příspěvků 

### ISSUE THREAD

**Issue by koc256** [lucien144/fyx#71]
- nové
- s poznámkou

Bylo by fajn, abych při letmém pohledu tyto příspěvky viděl i při rychlejším scrolování.

**Comment by lucien144** [comment]
Díky, zavírám, už to tu máme jako #15. Ohledně zvýraznění poznámek - nyní se ti vyplní ikona a to je vše. Osobně mi to vyhovuje, žluté zvýraznění jako má aktuální app mi nevyhovuje. Nicméně bych tohle probral s UX klukama co oni na to.
