### ISSUE TITLE
Výběr textu

### ISSUE THREAD

**Issue by koc256** [lucien144/fyx#73]
V TEXTAREA pro psaní příspěvků nefunguje výběr textu jako kdekoliv jinde. Není tam například možnost "Select" ale jen "Select All". A vůbec donutit tu nabídku zobrazit je kumšt.
![IMG_2013](https://user-images.githubusercontent.com/64221259/80514966-8a29c080-8981-11ea-975c-5bc9d0175d59.PNG)

**Comment by lucien144** [comment]
Nofix atm: flutter/flutter#17030
