### ISSUE TITLE
Chyba zobrazení příspěvku

### ISSUE THREAD

**Issue by fieldmanneasi** [lucien144/fyx#74]
**Zdroj:**
```<video src="https://i.imgur.com/Jzi267B.mp4" controls="controls" width="500"></video>```

---
*Verze: 0.3.0 (5)
iOS: iOS 13.3.1 iPhone*

**Comment by lucien144** [comment]
Díky za report. Zavírám, už to tu máme, ale posílej dál podobný problémy. Duplicate #53
